PREFIX : <http://cui.unig.ch/bda/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?ProduitIRI (SUM(?ComposantPrice) AS ?Total)
WHERE {
    SELECT DISTINCT *
    WHERE {
        ?ProduitIRI a :Produit ;
            :utilise/(:contient|:utilise)* ?ComposantIRI .
        
        ?ComposantIRI :prix ?ComposantPrice .
    }
}
GROUP BY ?ProduitIRI
ORDER BY DESC(?Total) ?ProduitIRI
