PREFIX : <http://cui.unig.ch/bda/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?p1 ?p2
WHERE {
    ?p1 a :Produit ;
        :utilise / (:contient | :utilise) * ?c .

    ?p2 a :Produit ;
        :utilise / (:contient | :utilise) * ?c .

    FILTER(STR(?p1) < STR(?p2))
}
ORDER BY ?p1 ?p2